// Generated by adsterra-code-handoff. Public browser configuration only.
// Domain: tradesquishydumplings.org
// Do not edit manually; rerun the handoff when placements change.
export const adsterraStaticConfig = {
  adsterraBannerId: "35604f19b01c981076db3c531dc7d4a5",
  adsterraBanner300x250Key: "35604f19b01c981076db3c531dc7d4a5",
  adsterraBanner300x250ScriptUrl: "https://www.highperformanceformat.com/35604f19b01c981076db3c531dc7d4a5/invoke.js",
  adsterraBanner320x50Key: "ff843c89f3424569d6ed3143615b398d",
  adsterraBanner320x50ScriptUrl: "https://www.highperformanceformat.com/ff843c89f3424569d6ed3143615b398d/invoke.js",
  adsterraBanner728x90Key: "efa1d2b81fe5bd22304a78e652ae75f9",
  adsterraBanner728x90ScriptUrl: "https://www.highperformanceformat.com/efa1d2b81fe5bd22304a78e652ae75f9/invoke.js",
  adsterraNative1Id: "container-5275573e75a351062bea211545be7f37",
  adsterraNative1ScriptUrl: "https://pl30200622.effectivecpmnetwork.com/5275573e75a351062bea211545be7f37/invoke.js",
  adsterraLeaderboardId: "efa1d2b81fe5bd22304a78e652ae75f9",
  adsterraEnablePopunder: false,
  adsterraEnableSocialBar: false,
  adsterraEnableStickyRail: false,
  adsterraPopunderDelayMs: 30000,
  adsterraPopunderMinPageViews: 2,
} as const;

export const adsterraStaticEnv = {
  NEXT_PUBLIC_ADSTERRA_BANNER_300X250_KEY: "35604f19b01c981076db3c531dc7d4a5",
  NEXT_PUBLIC_ADSTERRA_BANNER_300X250_SCRIPT_URL: "https://www.highperformanceformat.com/35604f19b01c981076db3c531dc7d4a5/invoke.js",
  NEXT_PUBLIC_ADSTERRA_BANNER_320X50_KEY: "ff843c89f3424569d6ed3143615b398d",
  NEXT_PUBLIC_ADSTERRA_BANNER_320X50_SCRIPT_URL: "https://www.highperformanceformat.com/ff843c89f3424569d6ed3143615b398d/invoke.js",
  NEXT_PUBLIC_ADSTERRA_BANNER_728X90_KEY: "efa1d2b81fe5bd22304a78e652ae75f9",
  NEXT_PUBLIC_ADSTERRA_BANNER_728X90_SCRIPT_URL: "https://www.highperformanceformat.com/efa1d2b81fe5bd22304a78e652ae75f9/invoke.js",
  NEXT_PUBLIC_ADSTERRA_ENABLE_POPUNDER: "false",
  NEXT_PUBLIC_ADSTERRA_ENABLE_SOCIAL_BAR: "false",
  NEXT_PUBLIC_ADSTERRA_ENABLE_STICKY_RAIL: "false",
  NEXT_PUBLIC_ADSTERRA_NATIVE_1_ID: "container-5275573e75a351062bea211545be7f37",
  NEXT_PUBLIC_ADSTERRA_NATIVE_1_SCRIPT_URL: "https://pl30200622.effectivecpmnetwork.com/5275573e75a351062bea211545be7f37/invoke.js",
  NEXT_PUBLIC_ADSTERRA_POPUNDER_DELAY_MS: "30000",
  NEXT_PUBLIC_ADSTERRA_POPUNDER_MIN_PAGEVIEWS: "2",
} as const;
